'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const APP_BASE=new URL('../../',document.currentScript.src).pathname;
const local=u=>u.startsWith('/')?APP_BASE+u.slice(1):u;
const pdfHref=p=>p.startsWith('http')?p:'/'+p;
const link=(href,label,cls='button')=>`<a class="${cls}" href="${esc(local(href))}">${esc(label)}</a>`;
let catalog,activePaper,activeQuestions=[],qIndex=0,searchOffset=0,lastParams='';
const cache=new Map();
async function get(url){const r=await fetch(local(url));if(!r.ok)throw Error(`Could not open ${url} (${r.status})`);return r.json();}
const labelDate=d=>d||'Date Not Identified';
const labelShift=s=>s?s.replace('_',' '):'Shift Not Identified';
const badge=t=>`<span class="badge">${esc(t)}</span>`;
function cards(list,render){return list.length?`<div class="grid">${list.map(render).join('')}</div>`:'<div class="empty">Status: Not Found. See the missing-paper report for collection details.</div>';}
function setYears(y){document.querySelectorAll('.year').forEach(b=>b.classList.toggle('active',b.dataset.year===String(y)));}
function browse(year,date,shift){
 setYears(year);const papers=catalog.papers.filter(p=>p.year===year);
 $('#crumbs').innerHTML=`${link('#','All years','')} <span>›</span> ${link('#year='+year,year,'')}`+(date!==undefined?` <span>›</span> ${link('#year='+year+'&date='+encodeURIComponent(date||'unknown'),labelDate(date),'')}`:'')+(shift!==undefined?` <span>›</span> ${esc(labelShift(shift))}`:'');
 if(date===undefined){const dates=[...new Set(papers.map(p=>p.exam_date))].sort();$('#browse').innerHTML=cards(dates,d=>`<article class="card"><h3>${esc(labelDate(d))}</h3><p>${papers.filter(p=>p.exam_date===d).length} collected papers</p>${link('#year='+year+'&date='+encodeURIComponent(d||'unknown'),'Choose date →')}</article>`);}
 else if(shift===undefined){const day=papers.filter(p=>p.exam_date===date);const shifts=[...new Set(day.map(p=>p.shift))].sort();$('#browse').innerHTML=cards(shifts,s=>`<article class="card"><h3>${esc(labelShift(s))}</h3><p>${day.filter(p=>p.shift===s).map(p=>p.stream.replaceAll('_',' & ')).join(' · ')}</p>${link('#year='+year+'&date='+encodeURIComponent(date||'unknown')+'&shift='+encodeURIComponent(s||'unknown'),'Choose shift →')}</article>`);}
 else{$('#browse').innerHTML=cards(papers.filter(p=>p.exam_date===date&&p.shift===shift),p=>`<article class="card"><h3>${esc(p.stream.replaceAll('_',' & '))}</h3><p>${p.question_count} question records · ${p.answers_mapped} mapped answers</p><p>${esc(p.source)}</p>${link('#paper='+encodeURIComponent(p.paper_id),'Open paper →')}</article>`);}
}
function images(items,alt){return (items||[]).map(a=>a.render_type==='pdf_region'?`<figure data-pdf="${esc(local('/'+a.path))}" data-page="${a.pdf_page}" data-bbox="${esc(JSON.stringify(a.bbox))}" data-alt="${esc(alt)}"><span class="note">Loading original PDF region…</span></figure>`:`<img src="${esc(local('/'+a.path))}" alt="${esc(alt)}" loading="lazy">`).join('');}
function renderQuestion(){
 const q=activeQuestions[qIndex];$('#qcontent').innerHTML=q?`<article class="question"><div>${badge(q.subject||'Subject Not Identified')}${badge(q.pdf_page?'PDF page '+q.pdf_page:'PDF page Not Identified')}${badge(q.extraction_status)}</div><h3>Question ${q.question_number}</h3>${q.question?`<div class="qtext">${esc(q.question)}</div>`:''}${images(q.question_images,'Original question '+q.question_number)}${!q.question&&!q.question_images.length?'<p>Question text Not Available. Open the original PDF.</p>':''}${q.options_embedded_in_question_image?'<p class="note">The options are included in the original question region above.</p>':'<ol class="options">'+ 'ABCD'.split('').map(a=>`<li class="${q.correct_answer===a?'correct':''}"><b>${a})</b><div>${q.options[a]?`<div class="qtext">${esc(q.options[a])}</div>`:''}${images(q.option_images[a],'Original option '+a)}${!q.options[a]&&!q.option_images[a].length?'<p class="note">Option text Not Available — consult the original PDF.</p>':''}</div></li>`).join('')+'</ol>'}${images(q.unassigned_images,'Original material requiring manual boundary review')}<p><b>Correct answer: ${esc(q.correct_answer||'Not Available')}</b> ${badge(q.answer_provenance.type.replaceAll('_',' '))}</p><div class="solution"><h4>Detailed solution</h4>${esc(q.solution||(q.solution_images?.length?'Published explanation preserved below from the original source PDF.':'Not Available — no reliable solution has been added for this question.'))}${images(q.solution_images,'Original published solution')}</div><div class="solution"><h4>EAPCET Shortcut</h4>${esc(q.eapcet_shortcut||'Not Available — not yet assessed.')}</div><div class="solution"><h4>Banda Gurthu</h4>${esc(q.banda_gurthu||'Not Available — no verified memory technique added.')}</div><p class="note">Chapter: ${esc(q.chapter||'Not Identified')} · Topic: ${esc(q.topic||'Not Identified')}</p><div class="source-info">${link('/'+q.source_paper+(q.pdf_page?'#page='+q.pdf_page:''),'Open original PDF at this question ↗')}<p>Source: ${esc(q.source)} · ${link(q.source_url,'Original source URL ↗','')}</p>${q.transcription_source_url?`<p>Published transcription: ${link(q.transcription_source_url,'Examsnet question ↗','')}</p>`:''}${q.solution_provenance?`<p>Explanation provenance: ${esc(q.solution_provenance.type||q.solution_provenance)}</p>`:''}</div></article>`:'<div class="empty">Question boundaries could not be reliably extracted. The original PDF is available above.</div>';
 if(window.renderMathInElement)window.renderMathInElement($('#qcontent'),{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}],throwOnError:false,strict:false,trust:false});
 if(window.renderPDFRegions)window.renderPDFRegions($('#qcontent'));
 $('#qnumber').value=String(qIndex);$('#prev').disabled=qIndex===0;$('#next').disabled=qIndex>=activeQuestions.length-1;
}
addEventListener('pdfrendererready',()=>window.renderPDFRegions?.($('#qcontent')||document.createElement('div')));
async function openPaper(id,qid){
 activePaper=catalog.papers.find(p=>p.paper_id===id);if(!activePaper)throw Error('Paper Not Found');
 if(!cache.has(id))cache.set(id,await get('/app/data/'+encodeURIComponent(id)+'.json'));activeQuestions=cache.get(id);qIndex=Math.max(0,activeQuestions.findIndex(q=>q.question_id===qid));const p=activePaper;
 $('#paper').hidden=false;$('#paper').innerHTML=`<div class="eyebrow">ORIGINAL PAPER · ${p.year}</div><h2>${esc(labelDate(p.exam_date))} · ${esc(labelShift(p.shift))}</h2><p>${esc(p.stream.replaceAll('_',' & '))} · ${p.pages} PDF pages · ${activeQuestions.length} extracted question records</p><div class="paper-actions">${link('/'+p.pdf_path,'Open original PDF ↗','button primary')}<button id="viewquestions">View questions</button><button id="viewanswers">View answers</button><button id="viewsolutions">View solutions</button>${(p.attachments||[]).map(a=>link(pdfHref(a.pdf_path),a.key_version?'Alternative paper / key version ↗':(a.subject?a.subject+' · ':'')+'Published paper / solutions ↗')).join('')}${p.answer_key_pdf?link('/'+p.answer_key_pdf,'Separate answer key ↗'):''}${link('/'+p.metadata_path,'Paper metadata ↗')}</div><details><summary>Source information and verification</summary><div class="source-info"><p>Source: ${esc(p.source)} · ${link(p.source_url,'Original Source URL ↗','')}</p><p>${link(p.download_url,'Original download URL ↗','')} · Answer key: ${esc(p.answer_key_status)} (${esc(p.answer_key_type)})</p><p>Date evidence: ${esc(p.date_verification)} · SHA-256: ${esc(p.sha256)}</p>${(p.additional_sources||[]).map(s=>`<p>Additional verified source: ${link(s.source_url,s.source,'')}</p>`).join('')}</div></details><div id="answerlist" hidden></div><div class="qnav"><button id="prev">← Previous</button><label for="qnumber">Question</label><select id="qnumber">${activeQuestions.map((q,i)=>`<option value="${i}">${q.question_number} · ${esc(q.subject||'?')}</option>`).join('')}</select><button id="next">Next →</button><span class="note">${p.answers_mapped} answers mapped</span></div><div id="qcontent"></div>`;
 const go=i=>{qIndex=i;location.hash='paper='+encodeURIComponent(id)+'&question='+encodeURIComponent(activeQuestions[i].question_id);};$('#prev').onclick=()=>go(qIndex-1);$('#next').onclick=()=>go(qIndex+1);$('#qnumber').onchange=e=>go(Number(e.target.value));$('#viewquestions').onclick=()=>$('#qcontent').scrollIntoView({behavior:'smooth'});$('#viewsolutions').onclick=()=>$('#qcontent .solution')?.scrollIntoView({behavior:'smooth'});$('#viewanswers').onclick=()=>{const el=$('#answerlist');el.hidden=!el.hidden;el.innerHTML=activeQuestions.map(q=>link('#paper='+encodeURIComponent(id)+'&question='+encodeURIComponent(q.question_id),`${q.question_number}: ${q.correct_answer||'N/A'}`,'badge')).join('');};renderQuestion();$('#paper').scrollIntoView({behavior:'smooth'});
}
function filters(){
 const fields=[['year','Year',catalog.years],['exam_date','Date',[]],['shift','Shift',['Shift_1','Shift_2']],['subject','Subject',['Mathematics','Physics','Chemistry','Botany','Zoology']],['chapter','Chapter',[]],['topic','Topic',[]]];
 $('#filters').innerHTML=fields.map(([k,t,values])=>`<label>${t}<select id="f_${k}"><option value="">All ${t.toLowerCase()}s</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`).join('');
 const dates=()=>{const year=$('#f_year').value,old=$('#f_exam_date').value;$('#f_exam_date').innerHTML='<option value="">All dates</option>'+[...new Set(catalog.papers.filter(p=>!year||p.year===Number(year)).map(p=>p.exam_date).filter(Boolean))].sort().map(d=>`<option value="${d}">${d}</option>`).join('');if([...$('#f_exam_date').options].some(o=>o.value===old))$('#f_exam_date').value=old;};$('#f_year').onchange=dates;dates();
 get('/database/filter_values.json').then(v=>{for(const k of ['chapter','topic'])$('#f_'+k).innerHTML='<option value="">All '+k+'s</option>'+v[k].map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');}).catch(()=>{});
 $('#searchform').onsubmit=e=>{e.preventDefault();searchOffset=0;const p=new URLSearchParams({q:$('#query').value});for(const k of ['year','exam_date','shift','subject','chapter','topic'])if($('#f_'+k).value)p.set(k,$('#f_'+k).value);lastParams=p.toString();search();};$('#reset').onclick=()=>{HTMLFormElement.prototype.reset.call($('#searchform'));dates();$('#results').innerHTML='';};
}
let staticIndex;
async function searchData(params){
 try{return await get('/api/search?'+params);}catch(e){
  if(!staticIndex)staticIndex=await get('/app/data/search_index.json');
  const p=new URLSearchParams(params),terms=(p.get('q')||'').toLowerCase().split(/\s+/).filter(Boolean),fields=['year','exam_date','shift','subject','chapter','topic','paper_id'];
  const matches=staticIndex.filter(q=>fields.every(k=>!p.get(k)||String(q[k])===p.get(k))&&terms.every(t=>q.search_text.includes(t)));
  return {total:matches.length,results:matches.slice(Number(p.get('offset')||0),Number(p.get('offset')||0)+40)};
 }
}
async function search(){
 $('#results').innerHTML='<p class="note">Searching…</p>';try{const d=await searchData(lastParams+'&offset='+searchOffset);$('#results').innerHTML=`<p>${d.total.toLocaleString()} matching questions</p>`+d.results.map(q=>`<article class="result"><h3>${link('#paper='+encodeURIComponent(q.paper_id)+'&question='+encodeURIComponent(q.question_id),`${q.year} · ${labelDate(q.exam_date)} · ${labelShift(q.shift)} · ${q.subject||'Unknown subject'} · Q${q.question_number}`,'')}</h3><p class="note">${esc(q.question?.slice(0,240)||'Original question preserved as an image. Open question to view.')}</p>${badge(q.source)}${q.chapter?badge(q.chapter):''}</article>`).join('')+`<div class="formrow"><button id="sprev" ${searchOffset===0?'disabled':''}>← Previous results</button><button id="snext" ${searchOffset+40>=d.total?'disabled':''}>Next results →</button></div>`;$('#sprev').onclick=()=>{searchOffset=Math.max(0,searchOffset-40);search();};$('#snext').onclick=()=>{searchOffset+=40;search();};}catch(e){$('#results').innerHTML=`<p class="error">${esc(e.message)}</p>`;}
}
async function route(){try{const p=new URLSearchParams(location.hash.slice(1));if(p.has('paper'))await openPaper(p.get('paper'),p.get('question'));else if(p.has('year')){const date=p.has('date')?(p.get('date')==='unknown'?null:p.get('date')):undefined,shift=p.has('shift')?(p.get('shift')==='unknown'?null:p.get('shift')):undefined;browse(Number(p.get('year')),date,shift);$('#paper').hidden=true;}else{$('#paper').hidden=true;$('#browse').innerHTML='';$('#crumbs').innerHTML='';setYears(null);}}catch(e){$('#browse').innerHTML=`<p class="error">${esc(e.message)}</p>`;}}
(async()=>{try{document.querySelectorAll('a[href^="/"]').forEach(a=>a.setAttribute('href',local(a.getAttribute('href'))));catalog=await get('/app/data/catalog.json');$('#years').innerHTML=catalog.years.map(y=>`<button class="year" data-year="${y}"><strong>${y}</strong><small>${catalog.papers.filter(p=>p.year===y).length} collected papers ↗</small></button>`).join('');document.querySelectorAll('.year').forEach(b=>b.onclick=()=>{location.hash='year='+b.dataset.year;});$('#stats').innerHTML=[[12,'Years checked'],[catalog.papers.length,'Original PDFs'],[catalog.papers.reduce((a,p)=>a+(p.question_count||0),0).toLocaleString(),'Question records']].map(([n,l])=>`<div class="stat"><b>${n}</b><span>${l}</span></div>`).join('');filters();addEventListener('hashchange',route);await route();}catch(e){$('#browse').innerHTML=`<p class="error">${esc(e.message)}</p>`;}})();
